version: 1.0.{build}.0

configuration: Release

platform: Any CPU

install:
- git submodule update --init --recursive

before_build:
- nuget restore ./Gelidus/Gelidus.sln

build:
  project: ./Gelidus/Gelidus.sln
  parallel: true
  verbosity: minimal
